name: CI/CD schedule_nbc

on:
  push:
    branches:
      - test
      - main

permissions:
  contents: write

jobs:
  deploy-and-test:
    runs-on: [self-hosted, schedule_nbc]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- ЛОГИКА ДЛЯ ТЕСТОВОЙ ВЕТКИ (ПОСТОЯННЫЙ ТЕСТОВЫЙ БОТ) ---
      - name: Deploy and Run Test Bot
        if: github.ref == 'refs/heads/test'
        run: |
          # 1. Синхронизируем код в локальную папку /test
          rsync -av --exclude='.git*' --exclude='config*' --exclude='allowed_users*' ./ /home/pi/app/schedule_nbc/test/
          
          cd /home/pi/app/schedule_nbc/test/
          chmod +x manage.sh
          
          # 2. Мягко перезапускаем тестового бота в фоне с изолированным путем.
          # env RUNNER_TRACKING_ID=0 отвязывает фоновый процесс от сессии Actions, оставляя его работать постоянно.
          env RUNNER_TRACKING_ID=0 ./manage.sh restart /dev/shm/schedule_nbc_tasks/test
          
          # 3. Даем системе 2 секунды на инициализацию и проверяем, что он успешно запустился и работает
          sleep 2
          ./manage.sh status

      # --- ЛОГИКА ДЛЯ РАБОЧЕЙ ВЕТКИ (ПРОДАКШН) ---
      - name: Deploy to Production Branch
        if: github.ref == 'refs/heads/main'
        run: |
          # 1. Синхронизируем код в продакшн, не затирая боевой config.json
          rsync -av --exclude='.git*' --exclude='debug.log' --exclude='config*' --exclude='allowed_users*' ./ /home/pi/app/schedule_nbc/prod/
          
          # 2. Автоматический перезапуск продакшн-бота
          cd /home/pi/app/schedule_nbc/prod/
          chmod +x manage.sh
          
          env RUNNER_TRACKING_ID=0 ./manage.sh restart || echo "Failed to restart"
          sleep 1
          ./manage.sh status
